use_frameworks!

target 'TestPods_Example' do
  pod 'TestPods', :path => '../'

  target 'TestPods_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  # pod 'TestPods', :podspec => '../TestPods.podspec'  # 指定podspec文件
  end
end
